# CPAC Data Configuration File
# Version 1.7.1
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025864/ses-1/anat/sub-0025864_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025864/ses-1/func/sub-0025864_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025864
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025864/ses-2/anat/sub-0025864_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025864/ses-2/func/sub-0025864_ses-2_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025864
  unique_id: '2'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025865/ses-1/anat/sub-0025865_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025865/ses-1/func/sub-0025865_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025865
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025865/ses-2/anat/sub-0025865_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025865/ses-2/func/sub-0025865_ses-2_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025865
  unique_id: '2'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025866/ses-1/anat/sub-0025866_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025866/ses-1/func/sub-0025866_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025866
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025866/ses-2/anat/sub-0025866_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025866/ses-2/func/sub-0025866_ses-2_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025866
  unique_id: '2'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025867/ses-1/anat/sub-0025867_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025867/ses-1/func/sub-0025867_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025867
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025867/ses-2/anat/sub-0025867_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025867/ses-2/func/sub-0025867_ses-2_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025867
  unique_id: '2'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025868/ses-1/anat/sub-0025868_ses-1_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025868/ses-1/func/sub-0025868_ses-1_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025868
  unique_id: '1'
- anat: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025868/ses-2/anat/sub-0025868_ses-2_run-1_T1w.nii.gz
  func:
    rest_run-1:
      scan: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/sub-0025868/ses-2/func/sub-0025868_ses-2_task-rest_run-1_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/CORR/RawDataBIDS/BNU_1/task-rest_bold.json
  site: BNU_1
  subject_id: 0025868
  unique_id: '2'
