# CPAC Data Configuration File
# Version 1.7.3.dev
#
# http://fcp-indi.github.io for more info.
#
# Tip: This file can be edited manually with a text editor for quick modifications.

- anat: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/anat/sub-A00028185_ses-NFB3_T1w.nii.gz
  func:
    MSIT:
      fmap_mag: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_magnitude1.nii.gz
      fmap_phase: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/fmap/sub-A00028185_ses-NFB3_phasediff.nii.gz
      scan: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/sub-A00028185/ses-NFB3/func/sub-A00028185_ses-NFB3_task-MSIT_bold.nii.gz
      scan_parameters: s3://fcp-indi/data/Projects/RocklandSample/RawDataBIDS/task-MSIT_bold.json
  site: site-1
  subject_id: A00028185
  unique_id: NFB3